# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@domain.com
baseurl: "/"
url: ""
brand_logo: "/assets/brand-logo.png"
# See _data/social_sites_db.yml for list of support sites.
# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - tests/
  - package.json
  - package-lock.json
include:
  # Jekyll >3.6 won't just let me include an excluded dir?! Grrr.
  - node_modules/jquery/dist/jquery.min.js
  - node_modules/bootstrap/dist/js/bootstrap.min.js
  - node_modules/bootstrap/dist/css/bootstrap.css
  - node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2
  - node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.woff
  - node_modules/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf
  - node_modules/font-awesome/css/font-awesome.min.css
# First page is home page. No link is shown for it. These pages must be in _fronts/.
fronts:
  - home.html
  - services.html
  - about.html
  - contact.html
default_front_titles: True
home_front_title: True
full_background_image: /assets/full-background-image.jpg
designer:
  name: sgpinkus
  url: https://github.io/sgpinkus/
google_analytics_id: UA-88127304-1
