# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@domain.com
# description: >
 # Write an awesome description for your new site here. You can edit this
baseurl: "/jekyll-scroll-spy-front-page"
url: ""
brand_logo: "assets/brand-logo.png"
# See _data/social_sites_db.yml for list of support sites.
social_link_urls:
  github: https://github.com/sam-at-github
  stack-overflow: https://stackoverflow.com/users/2038383/s-pinkus
# Build settings
markdown: kramdown
# theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - tests/
# First page is home page. No link is shown for it. These should also be excluded!
fronts:
  - home.html
  - services.html
  - about.html
  - contact.html
full_background_image: assets/full-background-image.jpg
designer:
  name: sam-at-github
  url: https://github.io/sam-at-github/
